#!/bin/bash
##SBATCH --partition=debug
##SBATCH --time=00:15:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=128000
#SBATCH --job-name="ccatsmall"
#SBATCH --output=ccatsmall.out
#SBATCH --mail-user=nitinnat@buffalo.edu
#SBATCH --mail-type=ALL
#SBATCH --requeue
#Specifies that the job will be requeued after a node failure.
#The default is that the job will not be requeued.

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR

module load python/anaconda-5.0.0
source activate py36
module load gcc/7.2.0

ulimit -s unlimited
#
python experiment.py --dataset ccat --reg_lambda 0.0001 --runs 1 --configfile config-pegasosCCATsmall.cfg
#
echo "All Done!"
