#!/bin/bash
##SBATCH --partition=debug
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=128000
#SBATCH --job-name="mnist"
#SBATCH --output=mnist-tf.out
#SBATCH --mail-user=nitinnat@buffalo.edu
#SBATCH --mail-type=ALL
#SBATCH --requeue
#SBATCH --exclusive
#SBATCH --constraint="CPU-E5-2660"
#Specifies that the job will be requeued after a node failure.
#The default is that the job will not be requeued.

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

cd $SLURM_SUBMIT_DIR
echo "working directory = "$SLURM_SUBMIT_DIR

module load python/anaconda-5.0.0
source activate py36
module load gcc/7.2.0

ulimit -s unlimited
#
python train_gadget.py --dataset mnist --reg_lambda 0.0000167 --max_iter 10000000000 --configfile config-pegasosMnist.cfg 
#
echo "All Done!"
